# Generated by Django 3.1.4 on 2020-12-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='store_id',
            field=models.IntegerField(default=0, verbose_name='Store ID'),
        ),
    ]
